[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "clDice"
version = "2024.02"

[tool.setuptools.packages.find]
where = ["."]

[tool.black]
line-length = 999
